// Package providers implements a generic HTTP execution engine for
// dynamically-configured travel data providers. Provider configurations
// are JSON files (typically generated by an LLM at runtime) that describe
// how to call an external API and map its response to the shared model types.
package providers

import (
	"fmt"
	"net/url"
	"time"
)

// ProviderConfig is the main configuration for a single external provider.
type ProviderConfig struct {
	ID              string            `json:"id"`
	Name            string            `json:"name"`
	Category        string            `json:"category"` // "hotel", "transport", "restaurant", ...
	Endpoint        string            `json:"endpoint"`
	Method          string            `json:"method"` // "GET" or "POST"
	Headers         map[string]string `json:"headers,omitempty"`
	QueryParams     map[string]string `json:"query_params,omitempty"`
	BodyTemplate    string            `json:"body_template,omitempty"`
	Auth            *AuthConfig       `json:"auth,omitempty"`
	ResponseMapping ResponseMapping   `json:"response_mapping"`
	RateLimit       RateLimitConfig   `json:"rate_limit"`
	TLS             TLSConfig         `json:"tls"`
	Cookies         CookieConfig      `json:"cookies"`
	Consent         *ConsentRecord    `json:"consent,omitempty"`
	LastSuccess     time.Time         `json:"last_success,omitempty"`
	LastError       string            `json:"last_error,omitempty"`
	ErrorCount      int               `json:"error_count,omitempty"`
	Version         int               `json:"version"`
}

// AuthConfig describes how to authenticate with the provider.
type AuthConfig struct {
	Type         string                `json:"type"` // "none", "header", "preflight"
	PreflightURL string                `json:"preflight_url,omitempty"`
	// PreflightMethod defaults to GET. Set to POST for OAuth2-style token exchange.
	PreflightMethod string             `json:"preflight_method,omitempty"`
	// PreflightBody is the request body for POST preflights (supports ${var} substitution).
	PreflightBody string               `json:"preflight_body,omitempty"`
	// PreflightHeaders are additional headers for the preflight request.
	PreflightHeaders map[string]string  `json:"preflight_headers,omitempty"`
	Extractions  map[string]Extraction  `json:"extractions,omitempty"`
}

// Extraction describes a regex extraction from a preflight response.
type Extraction struct {
	Pattern  string `json:"pattern"`  // regex with capture group
	Variable string `json:"variable"` // variable name for substitution
	Header   string `json:"header"`   // response header to extract from (empty = body)
}

// ResponseMapping describes how to extract results from the JSON response.
type ResponseMapping struct {
	ResultsPath string            `json:"results_path"` // dot-notation path to results array
	Fields      map[string]string `json:"fields"`       // model field -> JSON path mapping
}

// RateLimitConfig controls request pacing.
type RateLimitConfig struct {
	RequestsPerSecond float64 `json:"requests_per_second"`
	Burst             int     `json:"burst"`
}

// TLSConfig controls TLS fingerprint behaviour.
type TLSConfig struct {
	Fingerprint string `json:"fingerprint"` // "standard" or "chrome"
}

// CookieConfig controls how cookies are obtained.
type CookieConfig struct {
	Source  string `json:"source"`           // "none", "preflight", "browser"
	Browser string `json:"browser,omitempty"` // browser name when source is "browser"
}

// ConsentRecord tracks user consent for a provider domain.
type ConsentRecord struct {
	Granted   bool      `json:"granted"`
	Timestamp time.Time `json:"timestamp"`
	Domain    string    `json:"domain"`
}

// EndpointDomain extracts the host from the provider's endpoint URL.
// Returns an empty string if the URL cannot be parsed.
func (c *ProviderConfig) EndpointDomain() string {
	u, err := url.Parse(c.Endpoint)
	if err != nil {
		return ""
	}
	return u.Host
}

// Status returns a summary status string for the provider.
// "ok" if the last request succeeded, "error" if there are recent errors,
// "new" if no requests have been made yet.
func (c *ProviderConfig) Status() string {
	if c.ErrorCount > 0 {
		return "error"
	}
	if !c.LastSuccess.IsZero() {
		return "ok"
	}
	return "new"
}

// IsStale returns true if the provider has errors and no successful request
// in the last 24 hours.
func (c *ProviderConfig) IsStale() bool {
	if c.ErrorCount == 0 {
		return false
	}
	if c.LastSuccess.IsZero() {
		return c.ErrorCount > 0
	}
	return time.Since(c.LastSuccess) > 24*time.Hour
}

// validCategories lists accepted provider category values.
var validCategories = map[string]bool{
	"hotel":       true,
	"hotels":      true,
	"flight":      true,
	"flights":     true,
	"ground":      true,
	"restaurant":  true,
	"restaurants": true,
	"review":      true,
	"reviews":     true,
}

// Validate checks that required fields are present and values are valid.
func (c *ProviderConfig) Validate() error {
	if c.ID == "" {
		return fmt.Errorf("provider config: id is required")
	}
	if c.Name == "" {
		return fmt.Errorf("provider config: name is required")
	}
	if c.Category == "" {
		return fmt.Errorf("provider config: category is required")
	}
	if !validCategories[c.Category] {
		return fmt.Errorf("provider config: invalid category %q", c.Category)
	}
	if c.Endpoint == "" {
		return fmt.Errorf("provider config: endpoint is required")
	}
	if c.ResponseMapping.ResultsPath == "" {
		return fmt.Errorf("provider config: response_mapping.results_path is required")
	}
	return nil
}
